### ISSUE TITLE
Add even more robustness to errors

### ISSUE THREAD

**Issue by m93a** [yhatt/markdown-it-incremental-dom#39]
## Input:
```html
<a href="http://google.com"
  <x>
  style="display: none"
>
link
</a>
```

## Expected output:
```html
<a href="https://google.com" &lt;x="">
  style="display: none"
&gt;
link
</a>
```
[(live demo)](https://codepen.io/m93a/pen/QZBNbd)

## Actual output:
```
Error: elementOpen() can not be called between elementOpenStart() and elementOpenEnd().
```

**Comment by yhatt** [comment]
I had researched about this issue, but this case is seems not to be a problem of our plugin.

Your reported pair of code snippets is valid *as HTML, not Markdown.* [By following CommonMark](https://spec.commonmark.org/dingus/?text=%3Ca%20href%3D%22http%3A%2F%2Fgoogle.com%22%0A%20%20%3Cx%3E%0A%20%20style%3D%22display%3A%20none%22%0A%3E%0Alink%0A%3C%2Fa%3E%0A), we will expect to return *the converted HTML from Markdown* like below:

```html
<p>&lt;a href=&quot;http://google.com&quot;
<x>
style=&quot;display: none&quot;</p>
<blockquote>
</blockquote>
<p>link
</a></p>
```

Please read [CommonMark specs about HTML blocks](https://spec.commonmark.org/0.28/#html-blocks) to more details. We have not much incentive to support rendering invalid HTML with specific format, because it is already invalid!

In addition, we could not reproduce throwing any error of Incremental DOM by reported code. I have commited [the test of invalid Markdown HTML](https://github.com/yhatt/markdown-it-incremental-dom/commit/3de46e86434a513ea84739b1c649206779612266), but [it works](https://travis-ci.org/yhatt/markdown-it-incremental-dom/jobs/448193881#L519) correctly.
