### ISSUE TITLE
Can this library preserve the part of string that is not yet determined to a complete markdown?

### ISSUE THREAD

**Issue by weidehai** [yhatt/markdown-it-incremental-dom#69]
if my string is part by part and I am not sure whether the next part needs to be in Markdown syntax with last part or not, can I temporarily not output the text that might become Markdown syntax until it has enough information？

for example
first, i get string： “this is a `inline c”

and i render it, that will output textnode this is a `inline c

and then, i get string: "code`"

that will render to  textnode: (this is a) inlinecode: (inline code)

so it possible to reserve the ambiguity string？

so what i expect is render textnode: (this is a) fisrt  and output  inlinecode: (inline code) second

@yhatt @m93a hope to receive your help，thanks very much

**Comment by yhatt** [comment]
_This library renders the parsed tokens by markdown-it to DOM, and does not more than that._

You have to modify markdown-it parser to apply an ambiguous parsing, through other markdown-it plugins if it exists. (More specifically, you have to detect an `inline` token with probably incompleted code span, modify the content of the token and append `inline_code` token. [Inspect tokens in markdown-it demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22abc%60def%5Cn%5Cnabc%60def%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Atrue%2C%22_view%22%3A%22debug%22%7D%7D
))

However, I don't recommend to take this approach in general because it will break [the spec of Markdown parser](https://spec.commonmark.org/0.30/#example-348) and bring some edge cases you should take care.

**Comment by weidehai** [comment]
> _This library renders the parsed tokens by markdown-it to DOM, and does not more than that._
> 
> You have to modify markdown-it parser to apply an ambiguous parsing, through other markdown-it plugins if it exists. (More specifically, you have to detect an `inline` token with probably incompleted code span, modify the content of the token and append `inline_code` token. [Inspect tokens in markdown-it demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22abc%60def%5Cn%5Cnabc%60def%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Atrue%2C%22_view%22%3A%22debug%22%7D%7D))
> 
> However, I don't recommend to take this approach in general because it will break [the spec of Markdown parser](https://spec.commonmark.org/0.30/#example-348) and bring some edge cases you should take care.

thank you for your answer and i have another question, i reading this library source code and i find it parse full markdown string very time when i call md.renderToIncrementalDOM if i want reserve previous content，will this cause performance issues?
if i parse a string with 3000 length by increase 1 word each time，this is equivalent to parse (1+3000)*3000/2 = 4501500 characters
