### ISSUE TITLE
 performance issue by full string parse

### ISSUE THREAD

**Issue by weidehai** [yhatt/markdown-it-incremental-dom#70]
thank you for your answer and i have another question, i reading this library source code and i find it parse full markdown string very time when i call md.renderToIncrementalDOM if i want reserve previous content，will this cause performance issues?
if i parse a string with 3000 length by increase 1 word each time，this is equivalent to parse (1+3000)*3000/2 = 4501500 characters

**Comment by yhatt** [comment]
Again, _this library only renders the parsed tokens by markdown-it to DOM, and does not more than that._ We have no concern with markdown-it's parsing process and its performance.

**Comment by yhatt** [comment]
markdown-it had interested in the incremental parse and already discussed at markdown-it/markdown-ast-spec#5. IMO I don't think that the incremental parse brings the great value of perfomance, as same as [markdown-it author's opinion](https://github.com/markdown-it/markdown-ast-spec/issues/5#issuecomment-286649995), because a simple of change still may bring updates of the whole of AST even if applied the incremental parse. e.g. Incompleted code block, footnotes.

Actually the most of Markdown libraries do not take incremental parsing because the payoff is small for the complexity of implementation. AFAIK an only Markdown library that supports incremental parse is [ToastMark](https://toastui.medium.com/the-need-for-a-new-markdown-parser-and-why-e6a7f1826137#e38e), an internal Markdown parser used by [Toast UI's editor component](https://ui.toast.com/tui-editor).

**Comment by weidehai** [comment]
❤
